---
- name: Get all access control rules with all attributes - Page {{ page }}
  cisco.fmcansible.fmc_configuration:
    operation: "getAllAccessRule"
    path_params:
      containerUUID: "{{ container_uuid }}"
      domainUUID: "{{ domain_uuid }}"
    query_params:
      expanded: true
      limit: "{{ limit }}"
      offset: "{{ limit * page }}"
    register_as: access_control_rules

- name: Merge rules
  ansible.builtin.set_fact:
    all_access_rules: "{{ all_access_rules | default([]) + access_control_rules }}"
