- name: Get and list all FMC domains
  hosts: fmc_inventory
  connection: httpapi
  gather_facts: false
  vars:
    api_username: fmc.ansible.readonly
    #api_password: Abcd123$!

  tasks:
    #- name: Update username and password variables
      #no_log: true
      #ansible.builtin.set_fact:
        #ansible_user: "{{ api_username }}"
        #ansible_password: "{{ api_password }}"

    - name: Get FMC Domain List
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
    
    - name: DEBUG
      ansible.builtin.debug:
        var: domain
