- name: Get and list all FMC domains
  hosts: fmc_inventory
  connection: httpapi
  gather_facts: false
  vars:
    ansible_user: "{{ api_username }}"
    ansible_password: "{{ api_password }}"

  tasks:
    - name: Get FMC Domain List
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
    
    - name: DEBUG
      ansible.builtin.debug:
        var: domain
