---
- name: Test AAP credential
  hosts: fmc
  connection: local
  gather_facts: false

  vars:
    fmc_username: "{{ credential['username'] }}"
    fmc_password: "{{ credential['password'] }}"

  tasks:
    - name: Show injected credential variables
      debug:
        msg: "username={{ fmc_username | default('NOT SET') }}, password={{ fmc_password | default('NOT SET') }}"
