---
- name: Test AAP credential
  hosts: fmc
  connection: local
  gather_facts: false

  vars:
    fmc_username: "{{ ansible_use }}"
    fmc_password: "{{ ansible_password }}"

  tasks:
    - name: Debug fmc credentials (for troubleshooting only)
      debug:
        msg: "fmc_username: {{ fmc_username }}, fmc_password: {{ fmc_password }}"
